version: '3.2'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086 -storage_driver_user=root -storage_driver_password=root
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
    - influxsrv
  influxsrv:
    image: influxdb:1.8
    container_name: influxsrv
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB_DB=cadvisor
      # - INFLUXDB_HTTP_AUTH_ENABLED=true
      # - INFLUXDB_ADMIN_ENABLED=true
      # - INFLUXDB_ADMIN_USER=root
      # - INFLUXDB_ADMIN_PASSWORD=root
    volumes:
      - ./influxsrv_data:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro
# influx -host 127.0.0.1 -port 8086 -username root -password root
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxsrv:influxsrv
    volumes:
      - ./grafana_data/var:/var/lib/grafana
      - ./grafana_data/log:/var/log/grafana
      - /etc/localtime:/etc/localtime:ro
    environment:
      - INFLUXDB_HOST=localhost
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=cadvisor